export const CONTENT = {
  brand: {
    name: "NextGen Tech",
    tagline: "Your tech career starts here.",
    eyebrow: "🚀 Join 250+ students building with NextGen Tech",
    heroH1Line1: "YOUR TECH CAREER",
    heroH1Line2: "STARTS IN ONE DAY.",
    heroSubhead: "Hands-on IT training, simulated developer internships, and intensive bootcamps built for the next generation of engineers.",
    primaryCta: "Explore Programs",
    secondaryCta: "Start Your Journey",
    copyrightYear: 2026,
  },

  navLinks: [
    { label: "Home", href: "/" },
    { label: "Programs", href: "/programs" },
    { label: "Courses", href: "/courses" },
    { label: "Internships", href: "/internships" },
    { label: "Bootcamps", href: "/bootcamps" },
    { label: "Projects", href: "/projects" },
    { label: "Reviews", href: "/reviews" },
    { label: "For Colleges", href: "/colleges" },
  ],

  trustStats: [
    { number: 250, suffix: "+", label: "Active Students", icon: "Users" },
    { number: 6, suffix: "+", label: "Industry Programs", icon: "BookOpen" },
    { number: 25, suffix: "+", label: "Shipped Projects", icon: "Rocket" },
    { number: 5, suffix: "+", label: "Senior Mentors", icon: "Award" },
  ],

  partnerLogos: [
    { name: "Vercel", type: "Tech Partner" },
    { name: "AWS Academy", type: "Cloud Partner" },
    { name: "GitHub Education", type: "Platform" },
    { name: "IIT Delhi Tech Club", type: "College Partner" },
    { name: "BITS Pilani Innovation", type: "College Partner" },
    { name: "Microsoft for Startups", type: "Ecosystem" },
    { name: "Stripe", type: "Infrastructure" },
    { name: "Supabase", type: "Database Partner" },
  ],

  trackCategories: [
    {
      id: "web-dev",
      title: "Web Development",
      icon: "Code2",
      badge: "High Demand",
      description: "Master modern full-stack web engineering, React, Next.js, Node.js, databases, and shippable web apps.",
      courses: ["Web Development", "React & Next.js", "Node.js & Express", "Full Stack MERN", "Database Systems"],
      highlight: "Build and deploy production-grade responsive websites and full-stack web applications.",
    },
    {
      id: "hr",
      title: "HR & People Ops",
      icon: "Users",
      badge: "Essential",
      description: "Master talent acquisition, HR analytics, performance management systems, payroll operations, and employee engagement.",
      courses: ["HR Management", "Talent Acquisition", "HR Analytics", "Payroll & Compliance", "Employee Engagement"],
      highlight: "Learn end-to-end recruitment pipelines, ATS software, HR policy design, and employee lifecycle management.",
    },
    {
      id: "bde",
      title: "Business Development",
      icon: "Briefcase",
      badge: "High Growth",
      description: "Master lead generation, B2B client acquisition, market expansion strategies, pitch decks, and strategic partnerships.",
      courses: ["BDE Masterclass", "B2B Lead Generation", "Client Pitching & Negotiation", "CRM Operations", "Strategic Partnerships"],
      highlight: "Build sales funnels, qualify enterprise leads, draft client proposals, and close corporate deals.",
    },
    {
      id: "sales",
      title: "Corporate Sales",
      icon: "TrendingUp",
      badge: "High Pay",
      description: "Master consultative selling, objection handling, revenue pipeline management, closing techniques, and account management.",
      courses: ["Corporate Sales", "B2B & B2C Sales", "Sales Pipeline & CRM", "Closing Strategies", "Account Management"],
      highlight: "Execute cold outreach campaigns, conduct product demos, overcome objections, and drive top-line revenue.",
    },
    {
      id: "marketing",
      title: "Digital Marketing",
      icon: "Sparkles",
      badge: "Trending",
      description: "Master performance marketing, SEO, social media growth, email automation, content marketing, and brand strategy.",
      courses: ["Digital Marketing", "SEO & Content Strategy", "Performance Ads (Meta/Google)", "Social Media Strategy", "Marketing Analytics"],
      highlight: "Launch targeted ad campaigns, optimize conversion funnels, build organic brand reach, and track ROI.",
    },
    {
      id: "services",
      title: "IT & Client Services",
      icon: "Layers",
      badge: "Core Operations",
      description: "Master IT service delivery, client relationship management, SLA governance, technical support operations, and service desk management.",
      courses: ["Client Services", "IT Service Management", "SLA & Operations", "Customer Success", "Technical Support Desk"],
      highlight: "Manage client SLAs, coordinate service delivery teams, handle escalations, and drive client satisfaction.",
    },
  ],

  programCategories: [
    {
      id: "1day-training",
      title: "1-Day Training",
      priceRange: "₹99 – ₹499",
      description: "Learn a technology from industry experts in one intensive day.",
      badge: "Fastest Track",
      icon: "Zap",
      targetAnchor: "#programs",
    },
    {
      id: "internship-exp",
      title: "Internship Experience",
      priceRange: "₹499 – ₹1,999",
      description: "Work on a real-world project and experience an actual development workflow.",
      badge: "Most Practical",
      icon: "GitBranch",
      targetAnchor: "#internships",
    },
    {
      id: "bootcamps",
      title: "Bootcamps",
      priceRange: "₹999 – ₹4,999+",
      description: "Intensive multi-day programs to build job-ready skills.",
      badge: "Job Ready",
      icon: "Rocket",
      targetAnchor: "#bootcamps",
    },
  ],

  oneDayExperiences: {
    subtitle: "OUR 1-DAY FUNNEL METHODOLOGY",
    steps: [
      { number: "01", title: "Learn", desc: "Interactive live masterclass with senior engineers" },
      { number: "02", title: "Build", desc: "Write real production code for a hands-on project" },
      { number: "03", title: "Deploy", desc: "Ship your application live to Vercel/AWS before sunset" },
      { number: "04", title: "Certificate", desc: "Earn verified credentials sharable on LinkedIn" },
    ],
    programs: [
      {
        id: "web-dev-1day",
        title: "Web Development Sprint",
        icon: "Code",
        level: "Beginner Friendly",
        duration: "1 Day (6 Hours)",
        outcome: "Build & deploy a full stack responsive web application live on the web.",
        techStack: ["HTML5/CSS3", "JavaScript", "React", "Vercel"],
        price: "₹299",
        originalPrice: "₹999",
        popular: true,
      },
      {
        id: "hr-1day",
        title: "HR & Recruitment Sprint",
        icon: "Users",
        level: "Beginner Friendly",
        duration: "1 Day (5 Hours)",
        outcome: "Build an automated talent acquisition pipeline and candidate onboarding workflow.",
        techStack: ["HR Analytics", "ATS Tools", "Recruitment Funnels", "LinkedIn Recruiter"],
        price: "₹199",
        originalPrice: "₹799",
        popular: false,
      },
      {
        id: "bde-1day",
        title: "BDE & Lead Gen Sprint",
        icon: "Briefcase",
        level: "Intermediate",
        duration: "1 Day (5 Hours)",
        outcome: "Build a targeted B2B lead generation campaign and corporate client pitch deck.",
        techStack: ["LinkedIn Sales Nav", "Cold Emailing", "CRM Tools", "Proposal Decks"],
        price: "₹249",
        originalPrice: "₹899",
        popular: false,
      },
      {
        id: "sales-1day",
        title: "Corporate Sales Sprint",
        icon: "TrendingUp",
        level: "All Levels",
        duration: "1 Day (5 Hours)",
        outcome: "Master live sales pitching, objection handling, and CRM deal closing.",
        techStack: ["Salesforce/HubSpot", "Cold Calling", "Pitch Decks", "Deal Closing"],
        price: "₹249",
        originalPrice: "₹899",
        popular: false,
      },
      {
        id: "marketing-1day",
        title: "Digital Marketing Sprint",
        icon: "Sparkles",
        level: "All Levels",
        duration: "1 Day (5 Hours)",
        outcome: "Launch live targeted ad campaigns and build high-converting marketing funnels.",
        techStack: ["Google Ads", "Meta Ads", "SEO Tools", "Canva & Analytics"],
        price: "₹199",
        originalPrice: "₹799",
        popular: false,
      },
      {
        id: "services-1day",
        title: "IT & Client Services Sprint",
        icon: "Layers",
        level: "Beginner Friendly",
        duration: "1 Day (5 Hours)",
        outcome: "Set up SLA tracking, ticket management systems, and client support workflows.",
        techStack: ["Zendesk/Jira", "SLA Management", "Client Onboarding", "Support Desk"],
        price: "₹149",
        originalPrice: "₹599",
        popular: false,
      },
    ],
  },

  defaultProgramDetails: {
    title: "1-Day Full Stack Development Experience",
    duration: "1 Day",
    mode: "Online / Offline",
    certificate: "Yes",
    projects: "1",
    level: "Beginner",
    price: "₹299",
    originalPrice: "₹999",
    whatYoullLearn: [
      "HTML & CSS",
      "JavaScript",
      "React",
      "Backend basics",
      "APIs",
      "Database",
      "Deployment",
    ],
    whatYoullBuild: "🚀 Your First Full-Stack Web Application",
    schedule: [
      { time: "9:00 AM", activity: "Introduction & Setup" },
      { time: "10:00 AM", activity: "Frontend Architecture & React" },
      { time: "12:00 PM", activity: "Backend & Database Integration" },
      { time: "2:00 PM", activity: "Hands-on Project Building" },
      { time: "4:00 PM", activity: "Live Cloud Deployment" },
      { time: "5:00 PM", activity: "Certificate & Portfolio Release" },
    ],
  },

  projects: [
    {
      id: "proj-webdev",
      title: "Full Stack Web Application",
      category: "Web Development",
      techStack: "React + Node.js + Tailwind",
      outcome: "Production web platform with responsive user interfaces, REST APIs, and database integration.",
      tags: ["React", "Node.js", "Express", "Tailwind"],
      imageBg: "from-purple-900/70 to-slate-900/95",
      icon: "ShoppingCart",
      studentsCount: "35+ built",
      mockupSnippet: 'const app = express(); app.listen(3000, () => console.log("Server running"));',
    },
    {
      id: "proj-hr",
      title: "HR Recruitment & ATS Portal",
      category: "HR",
      techStack: "ATS Tools + HR Analytics",
      outcome: "Automated candidate sourcing dashboard, screening workflows, and HR compliance tracking.",
      tags: ["HR Analytics", "ATS", "Talent Sourcing", "Compliance"],
      imageBg: "from-cyan-900/70 to-slate-900/95",
      icon: "FileCheck",
      studentsCount: "25+ built",
      mockupSnippet: 'const candidate = await ats.processApplication({ name: "Rahul", role: "Developer" });',
    },
    {
      id: "proj-bde",
      title: "B2B Corporate Prospecting Campaign",
      category: "BDE",
      techStack: "LinkedIn Sales Nav + CRM Pipeline",
      outcome: "B2B corporate lead prospecting system, cold outreach sequences, and partnership pitch deck.",
      tags: ["Lead Gen", "B2B Sales", "CRM", "Outreach"],
      imageBg: "from-[#112d26] to-slate-900/95",
      icon: "PieChart",
      studentsCount: "30+ built",
      mockupSnippet: 'const leads = crm.pipeline.filter(lead => lead.score > 80);',
    },
    {
      id: "proj-sales",
      title: "Enterprise Sales Deal Deck & Pipeline",
      category: "Sales",
      techStack: "HubSpot CRM + Pitch Decks",
      outcome: "Corporate sales revenue pipeline, consultative sales scripts, and deal closing tracker.",
      tags: ["Sales Pipeline", "B2B Pitching", "Closing", "HubSpot"],
      imageBg: "from-[#2e1d3e] to-slate-900/95",
      icon: "BarChart3",
      studentsCount: "28+ built",
      mockupSnippet: 'SELECT deal_stage, SUM(deal_value) FROM sales_pipeline GROUP BY deal_stage;',
    },
    {
      id: "proj-marketing",
      title: "Performance Ad Campaign & Funnel",
      category: "Marketing",
      techStack: "Google Ads + Meta + SEO Analytics",
      outcome: "Multi-channel digital marketing campaign with SEO keyword map and conversion landing page.",
      tags: ["SEO", "Meta Ads", "Google Ads", "Google Analytics"],
      imageBg: "from-[#3e1d28] to-slate-900/95",
      icon: "Sparkles",
      studentsCount: "32+ built",
      mockupSnippet: 'const campaign = analytics.trackROI({ source: "google_ads", conversions: 145 });',
    },
    {
      id: "proj-services",
      title: "IT Client Service Desk Portal",
      category: "Services",
      techStack: "Zendesk / Helpdesk + SLA Tracking",
      outcome: "Structured IT client support portal with automated SLA tracking, ticket routing, and escalation management.",
      tags: ["Client Services", "SLA Management", "Service Desk", "Support"],
      imageBg: "from-[#1d2d3e] to-slate-900/95",
      icon: "Layers",
      studentsCount: "22+ built",
      mockupSnippet: 'ticket.onUpdate((status) => sla.calculateResolutionTime(status));',
    },
  ],

  internship: {
    badge: "CORPORATE & TECH WORKSPACE EXPERIENCE",
    headline: "Experience What It's Like to Work in Professional Domains.",
    subtext: "Skip passive lectures. Work in simulated 4-week corporate sprints with real project deliverables, mentor guidance, industry tools, and live campaign/code reviews.",
    features: [
      {
        title: "Agile Sprints & Milestone Tasks",
        desc: "Receive real domain assignments, scope sprint deliverables, and manage work on project boards.",
        icon: "CheckSquare",
      },
      {
        title: "Rigorous Mentor Feedback",
        desc: "Get line-by-line evaluation on project quality, strategy, communication, and execution from industry experts.",
        icon: "GitCommit",
      },
      {
        title: "Daily Standups & Workspace Channels",
        desc: "Collaborate in active domain channels, discuss strategies with team members, and demo weekly outputs.",
        icon: "MessageSquare",
      },
      {
        title: "Verified Internship Certificate & LOR",
        desc: "Receive a letter of recommendation, verified certificate, and shippable professional portfolio.",
        icon: "Award",
      },
    ],
    tracks: [
      {
        id: "web-dev-intern",
        title: "Web Development",
        icon: "Code",
        duration: "1 Day & More (Agile Sprint)",
        project: "Production E-Commerce & Full Stack Web Platform",
        skills: ["HTML5", "CSS3", "JavaScript", "React", "Node.js", "Tailwind CSS"],
        certificate: "Verified Internship Certificate + LOR",
        mentor: "Senior Web Architect @ TechCorp",
        badge: "Highest Demand",
        price: "₹999",
        image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=800&auto=format&fit=crop",
      },
      {
        id: "hr-intern",
        title: "HR (Human Resources)",
        icon: "Users",
        duration: "1 Day & More (Corporate Sprint)",
        project: "End-to-End Talent Acquisition & HR Operations System",
        skills: ["Talent Sourcing", "ATS Tools", "Screening & Interviews", "HR Policies", "Employee Engagement"],
        certificate: "Verified Internship Certificate + LOR",
        mentor: "Senior HR Lead @ Corporate Talent Hub",
        badge: "Core Domain",
        price: "₹999",
        image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=800&auto=format&fit=crop",
      },
      {
        id: "bde-intern",
        title: "BDE (Business Development Executive)",
        icon: "Briefcase",
        duration: "1 Day & More (Growth Sprint)",
        project: "B2B Client Acquisition & Corporate Partnership Campaign",
        skills: ["Lead Generation", "Market Prospecting", "Client Pitching", "CRM Management", "Contract Proposals"],
        certificate: "Verified Internship Certificate + LOR",
        mentor: "Head of Business Growth @ Global Services",
        badge: "High Growth",
        price: "₹1,199",
        image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?q=80&w=800&auto=format&fit=crop",
      },
      {
        id: "sales-intern",
        title: "Sales",
        icon: "TrendingUp",
        duration: "1 Day & More (Revenue Sprint)",
        project: "Corporate Sales Pipeline & B2B Revenue Generation Campaign",
        skills: ["Consultative Sales", "Pipeline Tracking", "Cold Outreach", "Product Demos", "Closing Strategies"],
        certificate: "Verified Internship Certificate + LOR",
        mentor: "Senior Sales Director @ Enterprise Solutions",
        badge: "High Revenue",
        price: "₹999",
        image: "https://images.unsplash.com/photo-1557804506-669a67965ba0?q=80&w=800&auto=format&fit=crop",
      },
      {
        id: "marketing-intern",
        title: "Marketing (Digital Marketing)",
        icon: "Sparkles",
        duration: "1 Day & More (Marketing Sprint)",
        project: "Multi-Channel Digital Marketing Campaign & Lead Funnel",
        skills: ["SEO Strategy", "Meta & Google Ads", "Content Marketing", "Social Media Growth", "Google Analytics"],
        certificate: "Verified Internship Certificate + LOR",
        mentor: "Digital Growth Strategist @ Brand Agency",
        badge: "Creative & Analytics",
        price: "₹999",
        image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=800&auto=format&fit=crop",
      },
      {
        id: "services-intern",
        title: "Services (IT & Business Services)",
        icon: "Layers",
        duration: "1 Day & More (Operations Sprint)",
        project: "Client Operations & SLA Support Service Desk Portal",
        skills: ["Client Relationship", "SLA Governance", "Service Desk", "Ticket Management", "Escalation Resolution"],
        certificate: "Verified Internship Certificate + LOR",
        mentor: "Head of Service Delivery @ Global IT Services",
        badge: "Operational Excellence",
        price: "₹999",
        image: "https://images.unsplash.com/photo-1581092921461-eab62e97a780?q=80&w=800&auto=format&fit=crop",
      },
    ],
    ctaText: "Apply for Internship",
  },

  bootcamps: [
    {
      id: "bootcamp-webdev-7",
      name: "Web Development Bootcamp",
      tagline: "7 Days → Zero to Full Stack Web Developer",
      duration: "7 Days",
      intensity: "Fast-Paced (15 hrs/wk)",
      price: "₹999",
      originalPrice: "₹2,999",
      popular: true,
      outcome: "Master web development fundamentals, React components, Node APIs, and live deployment.",
      modules: ["HTML/CSS", "JavaScript ES6+", "React", "Node.js", "Express", "Database", "Deployment"],
      includes: [
        "Live sessions",
        "Mentor support",
        "Assignments",
        "Real project",
        "Certificate",
        "Portfolio project",
        "GitHub setup",
      ],
      badge: "MOST POPULAR",
      ctaText: "Join Bootcamp",
    },
    {
      id: "bootcamp-bde-sales-7",
      name: "BDE & Corporate Sales Bootcamp",
      tagline: "7 Days → Corporate Deal Closer & Growth Strategist",
      duration: "7 Days",
      intensity: "Immersive (15 hrs/wk)",
      price: "₹999",
      originalPrice: "₹2,999",
      popular: false,
      outcome: "Master B2B lead generation, client pitching, consultative sales, and CRM deal closing.",
      modules: ["Lead Sourcing", "Cold Outreach", "B2B Pitching", "Objection Handling", "HubSpot CRM", "Closing"],
      includes: [
        "Live sessions",
        "Mentor support",
        "Assignments",
        "Real project",
        "Certificate",
        "Portfolio project",
        "Sales scripts",
      ],
      badge: "HIGH GROWTH",
      ctaText: "Join Bootcamp",
    },
    {
      id: "bootcamp-marketing-7",
      name: "Digital Marketing Bootcamp",
      tagline: "7 Days → Data-Driven Digital Marketer",
      duration: "7 Days",
      intensity: "Immersive (15 hrs/wk)",
      price: "₹999",
      originalPrice: "₹2,999",
      popular: false,
      outcome: "Master SEO optimization, Meta/Google ad campaigns, lead funnels, and marketing analytics.",
      modules: ["SEO Fundamentals", "Meta Ads", "Google Ads", "Content Strategy", "Conversion Funnels", "Analytics"],
      includes: [
        "Live sessions",
        "Mentor support",
        "Assignments",
        "Real project",
        "Certificate",
        "Portfolio project",
        "Ad templates",
      ],
      badge: "TRENDING",
      ctaText: "Join Bootcamp",
    },
    {
      id: "bootcamp-hr-7",
      name: "HR & People Operations Bootcamp",
      tagline: "7 Days → HR Generalist & Recruitment Specialist",
      duration: "7 Days",
      intensity: "Fast-Paced (15 hrs/wk)",
      price: "₹999",
      originalPrice: "₹2,999",
      popular: false,
      outcome: "Master talent acquisition, candidate screening, ATS software, HR compliance, and payroll.",
      modules: ["Talent Acquisition", "Screening & ATS", "Interviewing", "Employee Onboarding", "HR Compliance"],
      includes: [
        "Live sessions",
        "Mentor support",
        "Assignments",
        "Real project",
        "Certificate",
        "Portfolio project",
        "HR Toolkits",
      ],
      badge: "ESSENTIAL",
      ctaText: "Join Bootcamp",
    },
  ],

  howItWorks: [
    {
      step: "01",
      title: "Choose Your Track",
      desc: "Select a 1-Day Experience, Developer Internship, or Multi-Week Bootcamp aligned with your tech goals.",
    },
    {
      step: "02",
      title: "Hands-On Live Learning",
      desc: "Join live interactive sessions guided by veteran engineers from leading tech companies.",
    },
    {
      step: "03",
      title: "Build & Deploy Real Code",
      desc: "Write production-ready code, submit pull requests, and deploy your live apps to Vercel/AWS.",
    },
    {
      step: "04",
      title: "Get Certified & Hired",
      desc: "Earn verified credentials, build a standout GitHub portfolio, and unlock partner interview referrals.",
    },
  ],

  testimonials: [
    {
      id: "t1",
      name: "Rahul K.",
      role: "B.Tech CSE",
      program: "Full Stack 1-Day Experience",
      stars: 5,
      quote: "I built my first React project in a single day.",
    },
    {
      id: "t2",
      name: "Priya M.",
      role: "B.Tech IT",
      program: "Developer Internship Track",
      stars: 5,
      quote: "The internship felt like an actual company project.",
    },
    {
      id: "t3",
      name: "Ananya S.",
      role: "BCA",
      program: "AI Agent Builder 1-Day",
      stars: 5,
      quote: "The 1-Day AI Agent workshop was insane. Deployed my bot live before 5 PM!",
    },
    {
      id: "t4",
      name: "Vikram R.",
      role: "BE Data Science",
      program: "Data Analytics Sprint",
      stars: 5,
      quote: "Power BI & SQL sprint got me selected in campus placement interviews.",
    },
    {
      id: "t5",
      name: "Arjun T.",
      role: "B.Tech ECE",
      program: "MERN Stack Bootcamp",
      stars: 5,
      quote: "No theory fluff. Wrote 300+ lines of production TypeScript on day one.",
    },
    {
      id: "t6",
      name: "Sneha P.",
      role: "MCA",
      program: "Simulated Internship",
      stars: 5,
      quote: "Got a verified certificate + shippable GitHub portfolio link on LinkedIn!",
    },
  ],

  collegePartners: {
    badge: "B2B COLLEGE PARTNERSHIPS",
    headline: "Bring Industry Training to Your Campus",
    subtext: "Empower your institution's students with hands-on technical workshops, placement-readiness sprints, campus hackathons, and industry-accredited developer certifications.",
    offerings: [
      { title: "1-Day Workshops", desc: "Hands-on 6-hour build & deploy masterclasses guided by senior software engineers.", icon: "Laptop" },
      { title: "Hackathons", desc: "24-hour campus coding competitions with live mentor support & prizes.", icon: "Trophy" },
      { title: "Bootcamps", desc: "7 to 30-day intensive technical skill tracks aligned with modern hiring stacks.", icon: "Rocket" },
      { title: "Internship Programs", desc: "Simulated Agile developer workflows with Jira tickets, PR code reviews, and LORs.", icon: "Briefcase" },
      { title: "Placement Training", desc: "Mock technical interviews, system design, DSA problem solving, and resume polish.", icon: "GraduationCap" },
      { title: "AI Workshops", desc: "Generative AI APIs, LLMs, prompt engineering, and autonomous agent building.", icon: "Sparkles" },
      { title: "Industry Projects", desc: "Real client-grade production capstones shippable to student GitHub portfolios.", icon: "Code2" },
    ],
    ctaText: "Partner With Us",
  },

  faqs: [
    {
      category: 'Programs',
      question: "What programs does NextGen Tech offer?",
      answer: "We offer three core tracks: 1-Day Hands-On Experiences (build & deploy a real project in a single day), Simulated Developer Internships (4–6 weeks of real-world team workflows with code reviews, sprints & standups), and Intensive Bootcamps (multi-week deep-dive programs in Full Stack, AI/ML, Data Analytics, Cloud & DevOps, and UI/UX Design).",
    },
    {
      category: 'Programs',
      question: "Are these programs suitable for complete beginners with zero coding experience?",
      answer: "Absolutely. Every program starts from fundamentals. Our 1-Day Experiences use guided, step-by-step code templates with dedicated mentor assistance. You'll have a working, deployed application by the end of the day — no prior coding knowledge required.",
    },
    {
      category: 'Programs',
      question: "What is the difference between a 1-Day Experience, Internship, and Bootcamp?",
      answer: "1-Day Experiences are fast-paced hands-on sprints where you build and deploy one specific project in a single session. Internships simulate 4–6 weeks of real software team workflows including Jira boards, GitHub pull requests, code reviews, and async standups. Bootcamps are intensive multi-week comprehensive programs covering deep technical domains with capstone projects and portfolio building.",
    },
    {
      category: 'Certificates',
      question: "Do I receive a verified certificate upon completion?",
      answer: "Yes. Every graduate receives an encrypted, blockchain-verifiable digital certificate with a unique certificate ID and QR code. You can embed it directly into your LinkedIn profile, resume, or portfolio. Employers and colleges can verify authenticity instantly via our online verification portal.",
    },
    {
      category: 'Prerequisites',
      question: "What hardware, software, or accounts do I need before joining?",
      answer: "All you need is a laptop (Windows, macOS, or Linux), a modern browser (Chrome recommended), and a stable internet connection. We also ask you to create free accounts on GitHub, Vercel, and VS Code. All cloud development environments, tools, and resources are provided by us at no extra cost.",
    },
    {
      category: 'Internships',
      question: "How does the Simulated Developer Internship work?",
      answer: "You're placed in a team of 4–5 peers with a senior engineer as your mentor. Your team works in weekly sprints using a Kanban/Jira board, pushes code to GitHub repositories, submits pull requests for review, and participates in async daily standups. You receive detailed code review feedback, and your final capstone project goes into your professional portfolio.",
    },
    {
      category: 'Support',
      question: "What if I miss a live session or need extra help outside class hours?",
      answer: "All live sessions are recorded in HD and available in your student portal within 1 hour. You also have 24/7 access to our active Discord community with dedicated mentor channels for real-time code debugging, doubt resolution, and peer collaboration.",
    },
    {
      category: 'Pricing',
      question: "Are there group discounts for college batches or student clubs?",
      answer: "Yes! We offer special college group pricing and campus ambassador discounts for groups of 5 or more students. We also partner with Training & Placement Officers (TPOs) for semester-integrated programs. Use our 'Partner With Us' form or contact us directly to request a custom group pass.",
    },
    {
      category: 'Pricing',
      question: "What is the refund policy?",
      answer: "We offer a 100% money-back guarantee for all 1-Day Experiences if you request a refund within 2 hours of the workshop start time. For Internships and Bootcamps, a full refund is available within the first 48 hours of enrollment. No questions asked.",
    },
    {
      category: 'Placements',
      question: "Does NextGen Tech help with job placements or career support?",
      answer: "While we don't guarantee placements, we provide end-to-end career support including resume building, LinkedIn profile optimization, portfolio reviews, mock interview sessions, and access to our hiring partner network. Many of our alumni have secured roles at startups, product companies, and service firms within weeks of completing our programs.",
    },
  ],

  finalCta: {
    headline: "YOUR FIRST TECH EXPERIENCE IS ONE DAY AWAY.",
    subtext: "No boring lectures. No passive videos. Write real code, deploy live applications, and launch your software career today.",
    ctaText: "START LEARNING NOW",
    trustBadge: "⚡ Over 500+ students already enrolled. No prior experience required.",
  },

  footer: {
    tagline: "Empowering the next generation of software engineers through hands-on, high-impact technical training.",
    columns: [
      {
        title: "Programs",
        links: [
          { label: "1-Day Experiences", href: "/programs" },
          { label: "Program Details & Syllabus", href: "/program-details" },
          { label: "Developer Internships", href: "/internships" },
          { label: "Technical Bootcamps", href: "/bootcamps" },
          { label: "MERN Stack Sprint", href: "/bootcamps" },
        ],
      },
      {
        title: "Technologies",
        links: [
          { label: "Development", href: "/courses" },
          { label: "Data Analytics", href: "/courses" },
          { label: "AI & Machine Learning", href: "/courses" },
          { label: "UI/UX Design", href: "/courses" },
          { label: "Cloud & DevOps", href: "/courses" },
        ],
      },
      {
        title: "Company & Portals",
        links: [
          { label: "About Us", href: "/about" },
          { label: "Trainers & Mentors", href: "/trainers" },
          { label: "Certificates", href: "/certificates" },
          { label: "FAQs", href: "/faq" },
          { label: "Student Login / Signup", href: "/login" },
        ],
      },
      {
        title: "Student Dashboard",
        links: [
          { label: "My Dashboard", href: "/dashboard" },
          { label: "My Courses", href: "/my-courses" },
          { label: "My Certificates", href: "/my-certificates" },
          { label: "Admin Console", href: "/admin" },
          { label: "For Colleges & TPOs", href: "/colleges" },
        ],
      },
    ],
    socials: [
      { name: "GitHub", href: "#", icon: "Github" },
      { name: "Twitter", href: "#", icon: "Twitter" },
      { name: "LinkedIn", href: "#", icon: "Linkedin" },
      { name: "YouTube", href: "#", icon: "Youtube" },
      { name: "Discord", href: "#", icon: "MessageSquare" },
    ],
  },
};
