export const CONTENT = {
  brand: {
    name: "NextGen Tech",
    tagline: "Your tech career starts here.",
    eyebrow: "🚀 Join 250+ students building with NextGen Tech",
    heroH1Line1: "YOUR TECH CAREER",
    heroH1Line2: "STARTS IN ONE DAY.",
    heroSubhead: "Hands-on IT training, simulated developer internships, and intensive bootcamps built for the next generation of engineers.",
    primaryCta: "Explore Programs",
    secondaryCta: "Start Your Journey",
    copyrightYear: 2026,
  },

  navLinks: [
    { label: "Home", href: "/" },
    { label: "Programs", href: "/programs" },
    { label: "Courses", href: "/courses" },
    { label: "Internships", href: "/internships" },
    { label: "Bootcamps", href: "/bootcamps" },
    { label: "Projects", href: "/projects" },
    { label: "Reviews", href: "/reviews" },
    { label: "For Colleges", href: "/colleges" },
  ],

  trustStats: [
    { number: 250, suffix: "+", label: "Active Students", icon: "Users" },
    { number: 6, suffix: "+", label: "Industry Programs", icon: "BookOpen" },
    { number: 25, suffix: "+", label: "Shipped Projects", icon: "Rocket" },
    { number: 5, suffix: "+", label: "Senior Mentors", icon: "Award" },
  ],

  partnerLogos: [
    { name: "Vercel", type: "Tech Partner" },
    { name: "AWS Academy", type: "Cloud Partner" },
    { name: "GitHub Education", type: "Platform" },
    { name: "IIT Delhi Tech Club", type: "College Partner" },
    { name: "BITS Pilani Innovation", type: "College Partner" },
    { name: "Microsoft for Startups", type: "Ecosystem" },
    { name: "Stripe", type: "Infrastructure" },
    { name: "Supabase", type: "Database Partner" },
  ],

  trackCategories: [
    {
      id: "dev",
      title: "Development",
      icon: "Code2",
      badge: "Highest Demand",
      description: "Master modern full-stack web engineering, backend APIs, object-oriented programming, and scalable architecture.",
      courses: ["Full Stack Development", "MERN", "Python", "Java", "React", "Node.js"],
      highlight: "Build and deploy production-ready web apps, REST APIs, and enterprise backend systems.",
    },
    {
      id: "data",
      title: "Data",
      icon: "BarChart3",
      badge: "Core Skill",
      description: "Transform raw datasets into actionable executive insights, automated SQL pipelines, and Power BI dashboards.",
      courses: ["Data Analytics", "Power BI", "SQL", "Python for Data"],
      highlight: "Clean financial datasets, query relational databases, and publish interactive BI dashboards.",
    },
    {
      id: "ai",
      title: "AI",
      icon: "Sparkles",
      badge: "Trending",
      description: "Harness Generative AI APIs, LLM prompt engineering, machine learning models, and autonomous coding tools.",
      courses: ["Generative AI", "AI Tools", "Machine Learning", "Prompt Engineering"],
      highlight: "Create autonomous AI agents, fine-tune models, and integrate GPT/Claude APIs into software products.",
    },
    {
      id: "design",
      title: "Design",
      icon: "Layout",
      badge: "High Pay",
      description: "Craft pixel-perfect user interfaces, interactive Figma design systems, and responsive modern web experiences.",
      courses: ["UI/UX", "Figma", "Web Design"],
      highlight: "Design production design systems, wireframes, micro-interactions, and conversion-focused websites.",
    },
    {
      id: "cloud",
      title: "Cloud",
      icon: "Cloud",
      badge: "Essential",
      description: "Build automated CI/CD pipelines, containerize microservices with Docker, and manage AWS & Azure cloud infrastructure.",
      courses: ["AWS", "Azure", "DevOps", "Docker"],
      highlight: "Configure automated deployments, manage serverless clusters, and scale cloud infrastructure.",
    },
  ],

  programCategories: [
    {
      id: "1day-training",
      title: "1-Day Training",
      priceRange: "₹99 – ₹499",
      description: "Learn a technology from industry experts in one intensive day.",
      badge: "Fastest Track",
      icon: "Zap",
      targetAnchor: "#programs",
    },
    {
      id: "internship-exp",
      title: "Internship Experience",
      priceRange: "₹499 – ₹1,999",
      description: "Work on a real-world project and experience an actual development workflow.",
      badge: "Most Practical",
      icon: "GitBranch",
      targetAnchor: "#internships",
    },
    {
      id: "bootcamps",
      title: "Bootcamps",
      priceRange: "₹999 – ₹4,999+",
      description: "Intensive multi-day programs to build job-ready skills.",
      badge: "Job Ready",
      icon: "Rocket",
      targetAnchor: "#bootcamps",
    },
  ],

  oneDayExperiences: {
    subtitle: "OUR 1-DAY FUNNEL METHODOLOGY",
    steps: [
      { number: "01", title: "Learn", desc: "Interactive live masterclass with senior engineers" },
      { number: "02", title: "Build", desc: "Write real production code for a hands-on project" },
      { number: "03", title: "Deploy", desc: "Ship your application live to Vercel/AWS before sunset" },
      { number: "04", title: "Certificate", desc: "Earn verified credentials sharable on LinkedIn" },
    ],
    programs: [
      {
        id: "fullstack-1day",
        title: "Full Stack App in 1 Day",
        icon: "Code",
        level: "Beginner Friendly",
        duration: "1 Day (6 Hours)",
        outcome: "Build & deploy a full stack SaaS app with live authentication and database.",
        techStack: ["Next.js", "TypeScript", "Tailwind", "Supabase"],
        price: "₹299",
        originalPrice: "₹999",
        popular: true,
      },
      {
        id: "ai-1day",
        title: "AI Agent Builder",
        icon: "Bot",
        level: "Intermediate",
        duration: "1 Day (6 Hours)",
        outcome: "Build an autonomous AI coding assistant powered by Claude and OpenAI APIs.",
        techStack: ["Python", "OpenAI API", "LangChain", "Streamlit"],
        price: "₹399",
        originalPrice: "₹1,199",
        popular: false,
      },
      {
        id: "data-1day",
        title: "Data Analytics Sprint",
        icon: "PieChart",
        level: "Beginner Friendly",
        duration: "1 Day (5 Hours)",
        outcome: "Clean a 100k-row financial dataset and publish an interactive executive dashboard.",
        techStack: ["Python", "Pandas", "Streamlit", "Plotly"],
        price: "₹199",
        originalPrice: "₹799",
        popular: false,
      },
      {
        id: "uiux-1day",
        title: "Framer SaaS Landing Page",
        icon: "Palette",
        level: "All Levels",
        duration: "1 Day (5 Hours)",
        outcome: "Design and publish a responsive 3D-effect portfolio & SaaS landing page.",
        techStack: ["Figma", "Framer", "CSS Motion", "Design Tokens"],
        price: "₹149",
        originalPrice: "₹599",
        popular: false,
      },
    ],
  },

  defaultProgramDetails: {
    title: "1-Day Full Stack Development Experience",
    duration: "1 Day",
    mode: "Online / Offline",
    certificate: "Yes",
    projects: "1",
    level: "Beginner",
    price: "₹299",
    originalPrice: "₹999",
    whatYoullLearn: [
      "HTML & CSS",
      "JavaScript",
      "React",
      "Backend basics",
      "APIs",
      "Database",
      "Deployment",
    ],
    whatYoullBuild: "🚀 Your First Full-Stack Web Application",
    schedule: [
      { time: "9:00 AM", activity: "Introduction & Setup" },
      { time: "10:00 AM", activity: "Frontend Architecture & React" },
      { time: "12:00 PM", activity: "Backend & Database Integration" },
      { time: "2:00 PM", activity: "Hands-on Project Building" },
      { time: "4:00 PM", activity: "Live Cloud Deployment" },
      { time: "5:00 PM", activity: "Certificate & Portfolio Release" },
    ],
  },

  projects: [
    {
      id: "proj-ecommerce",
      title: "E-Commerce Website",
      category: "Full Stack",
      techStack: "React + Node.js + MongoDB",
      outcome: "Full-stack online store with live cart management, REST APIs, product database, and checkout flow.",
      tags: ["React", "Node.js", "MongoDB", "Express"],
      imageBg: "from-purple-900/70 to-slate-900/95",
      icon: "ShoppingCart",
      studentsCount: "25+ built",
      mockupSnippet: 'const cart = await db.cart.insert({ item: "Nike Air", price: 299 });',
    },
    {
      id: "proj-ai-resume",
      title: "AI Resume Analyzer",
      category: "AI & Python",
      techStack: "Python + AI",
      outcome: "Intelligent PDF parser & ATS resume scoring agent powered by OpenAI APIs and Python.",
      tags: ["Python", "OpenAI API", "Streamlit", "PDF Parser"],
      imageBg: "from-cyan-900/70 to-slate-900/95",
      icon: "FileCheck",
      studentsCount: "20+ built",
      mockupSnippet: 'score = ai.analyze_resume(pdf_text, job_desc="Full Stack Dev");',
    },
    {
      id: "proj-expense-tracker",
      title: "Expense Tracker",
      category: "Frontend & API",
      techStack: "React + Node",
      outcome: "Personal finance tracker with dark-mode analytics, expense logging, and budget breakdown charts.",
      tags: ["React", "Node.js", "Chart.js", "Tailwind"],
      imageBg: "from-[#112d26] to-slate-900/95",
      icon: "PieChart",
      studentsCount: "18+ built",
      mockupSnippet: 'const summary = calculateMonthlyExpenses(transactions);',
    },
    {
      id: "proj-business-dashboard",
      title: "Business Dashboard",
      category: "Data & Analytics",
      techStack: "Power BI + SQL",
      outcome: "Executive sales & revenue intelligence dashboard backed by automated SQL database queries.",
      tags: ["Power BI", "SQL", "Data Pipelines", "DAX"],
      imageBg: "from-[#2e1d3e] to-slate-900/95",
      icon: "BarChart3",
      studentsCount: "15+ built",
      mockupSnippet: 'SELECT category, SUM(revenue) FROM sales GROUP BY category;',
    },
  ],

  internship: {
    badge: "DEVELOPER WORKSPACE EXPERIENCE",
    headline: "Experience What It's Like to Work in Tech.",
    subtext: "Skip passive video lectures. Work in simulated 4-week Agile sprints with real Jira tickets, GitHub pull requests, senior engineer code reviews, and live production deployments.",
    features: [
      {
        title: "Agile Kanban & Jira Tickets",
        desc: "Receive real user stories, scope sprint tasks, and manage feature boards like tech startups.",
        icon: "CheckSquare",
      },
      {
        title: "Rigorous Pull Request Reviews",
        desc: "Get line-by-line feedback on code quality, security, performance, and clean architecture from senior devs.",
        icon: "GitCommit",
      },
      {
        title: "Daily Standups & Discord Workspace",
        desc: "Collaborate in active developer channels, debug blockers with teammates, and demo features weekly.",
        icon: "MessageSquare",
      },
      {
        title: "Verified Internship Certificate",
        desc: "Receive a letter of recommendation, verified certificate, and shippable GitHub portfolio.",
        icon: "Award",
      },
    ],
    tracks: [
      {
        id: "web-dev-intern",
        title: "Web Development",
        icon: "Code",
        duration: "4 Weeks (Agile Sprint)",
        project: "Production E-Commerce Platform with Cart & Payment Flow",
        skills: ["HTML5", "CSS3", "JavaScript ES6+", "React", "Tailwind"],
        certificate: "Verified Internship Certificate + LOR",
        mentor: "Senior Frontend Architect @ TechCorp",
        badge: "Most Popular",
        price: "₹999",
      },
      {
        id: "fullstack-intern",
        title: "Full Stack Development",
        icon: "Layers",
        duration: "4 Weeks (Agile Sprint)",
        project: "Multi-tenant SaaS App with Supabase Auth & PostgreSQL",
        skills: ["Next.js 14", "TypeScript", "Node.js", "Supabase", "REST APIs"],
        certificate: "Verified Internship Certificate + LOR",
        mentor: "Lead Full Stack Engineer @ Vercel Partner",
        badge: "High Hiring Rate",
        price: "₹1,499",
      },
      {
        id: "python-intern",
        title: "Python Development",
        icon: "Terminal",
        duration: "4 Weeks (Agile Sprint)",
        project: "Automated Data Scraper Engine & REST Microservice",
        skills: ["Python 3.12", "FastAPI", "BeautifulSoup", "Docker", "Git"],
        certificate: "Verified Internship Certificate + LOR",
        mentor: "Core Backend Engineer @ CloudScale",
        badge: "Core Backend",
        price: "₹999",
      },
      {
        id: "data-analytics-intern",
        title: "Data Analytics",
        icon: "BarChart3",
        duration: "4 Weeks (Agile Sprint)",
        project: "Executive Business Intelligence Dashboard & Data Pipeline",
        skills: ["Python", "Pandas", "SQL", "Power BI", "Plotly"],
        certificate: "Verified Internship Certificate + LOR",
        mentor: "Senior Data Scientist @ AnalyticsHub",
        badge: "High Growth",
        price: "₹1,199",
      },
      {
        id: "uiux-intern",
        title: "UI/UX",
        icon: "Layout",
        duration: "4 Weeks (Agile Sprint)",
        project: "Enterprise Design System & Responsive SaaS Prototypes",
        skills: ["Figma", "Design Tokens", "Wireframing", "Micro-Interactions"],
        certificate: "Verified Internship Certificate + LOR",
        mentor: "Principal Product Designer @ Framer Network",
        badge: "Creative Tech",
        price: "₹999",
      },
      {
        id: "aiml-intern",
        title: "AI & ML",
        icon: "Sparkles",
        duration: "4 Weeks (Agile Sprint)",
        project: "Autonomous AI Agent Assistant & LLM API Integration",
        skills: ["Python", "OpenAI API", "LangChain", "PyTorch", "Streamlit"],
        certificate: "Verified Internship Certificate + LOR",
        mentor: "AI Research Lead @ GenAI Labs",
        badge: "Cutting Edge",
        price: "₹1,999",
      },
    ],
    ctaText: "Apply for Internship",
  },

  bootcamps: [
    {
      id: "bootcamp-mern-7",
      name: "MERN Stack Bootcamp",
      tagline: "7 Days → Beginner to Project Ready",
      duration: "7 Days",
      intensity: "Fast-Paced (15 hrs/wk)",
      price: "₹999",
      originalPrice: "₹2,999",
      popular: true,
      outcome: "Master full-stack MERN architecture from HTML basics to cloud database deployment.",
      modules: ["HTML", "CSS", "JS", "React", "Node", "Express", "MongoDB", "Deployment"],
      includes: [
        "Live sessions",
        "Mentor support",
        "Assignments",
        "Real project",
        "Certificate",
        "Portfolio project",
        "GitHub setup",
      ],
      badge: "MOST POPULAR",
      ctaText: "Join Bootcamp",
    },
    {
      id: "bootcamp-14",
      name: "AI & Full Stack 14-Day Builder",
      tagline: "14 Days → Production SaaS Engineer",
      duration: "14 Days",
      intensity: "Immersive (25 hrs/wk)",
      price: "₹1,999",
      originalPrice: "₹5,999",
      popular: false,
      outcome: "Full Stack & AI integration: build multi-tenant SaaS with OpenAI APIs & Supabase.",
      modules: ["TypeScript", "Next.js 14", "Tailwind", "Supabase", "OpenAI API", "Vercel"],
      includes: [
        "Live sessions",
        "Mentor support",
        "Assignments",
        "Real project",
        "Certificate",
        "Portfolio project",
        "GitHub setup",
      ],
      badge: "AI Powered",
      ctaText: "Join Bootcamp",
    },
    {
      id: "bootcamp-30",
      name: "30-Day Career Launch",
      tagline: "30 Days → Zero to Job-Ready Engineer",
      duration: "30 Days",
      intensity: "Full Immersion (35 hrs/wk)",
      price: "₹4,999",
      originalPrice: "₹12,999",
      popular: false,
      outcome: "Complete software engineering transformation with 6 portfolio projects & internship.",
      modules: ["System Design", "Microservices", "Docker", "AWS", "CI/CD", "Placement Prep"],
      includes: [
        "Live sessions",
        "Mentor support",
        "Assignments",
        "Real project",
        "Certificate",
        "Portfolio project",
        "GitHub setup",
      ],
      badge: "Maximum Impact",
      ctaText: "Join Bootcamp",
    },
  ],

  howItWorks: [
    {
      step: "01",
      title: "Choose Your Track",
      desc: "Select a 1-Day Experience, Developer Internship, or Multi-Week Bootcamp aligned with your tech goals.",
    },
    {
      step: "02",
      title: "Hands-On Live Learning",
      desc: "Join live interactive sessions guided by veteran engineers from leading tech companies.",
    },
    {
      step: "03",
      title: "Build & Deploy Real Code",
      desc: "Write production-ready code, submit pull requests, and deploy your live apps to Vercel/AWS.",
    },
    {
      step: "04",
      title: "Get Certified & Hired",
      desc: "Earn verified credentials, build a standout GitHub portfolio, and unlock partner interview referrals.",
    },
  ],

  testimonials: [
    {
      id: "t1",
      name: "Rahul K.",
      role: "B.Tech CSE",
      program: "Full Stack 1-Day Experience",
      stars: 5,
      quote: "I built my first React project in a single day.",
    },
    {
      id: "t2",
      name: "Priya M.",
      role: "B.Tech IT",
      program: "Developer Internship Track",
      stars: 5,
      quote: "The internship felt like an actual company project.",
    },
    {
      id: "t3",
      name: "Ananya S.",
      role: "BCA",
      program: "AI Agent Builder 1-Day",
      stars: 5,
      quote: "The 1-Day AI Agent workshop was insane. Deployed my bot live before 5 PM!",
    },
    {
      id: "t4",
      name: "Vikram R.",
      role: "BE Data Science",
      program: "Data Analytics Sprint",
      stars: 5,
      quote: "Power BI & SQL sprint got me selected in campus placement interviews.",
    },
    {
      id: "t5",
      name: "Arjun T.",
      role: "B.Tech ECE",
      program: "MERN Stack Bootcamp",
      stars: 5,
      quote: "No theory fluff. Wrote 300+ lines of production TypeScript on day one.",
    },
    {
      id: "t6",
      name: "Sneha P.",
      role: "MCA",
      program: "Simulated Internship",
      stars: 5,
      quote: "Got a verified certificate + shippable GitHub portfolio link on LinkedIn!",
    },
  ],

  collegePartners: {
    badge: "B2B COLLEGE PARTNERSHIPS",
    headline: "Bring Industry Training to Your Campus",
    subtext: "Empower your institution's students with hands-on technical workshops, placement-readiness sprints, campus hackathons, and industry-accredited developer certifications.",
    offerings: [
      { title: "1-Day Workshops", desc: "Hands-on 6-hour build & deploy masterclasses guided by senior software engineers.", icon: "Laptop" },
      { title: "Hackathons", desc: "24-hour campus coding competitions with live mentor support & prizes.", icon: "Trophy" },
      { title: "Bootcamps", desc: "7 to 30-day intensive technical skill tracks aligned with modern hiring stacks.", icon: "Rocket" },
      { title: "Internship Programs", desc: "Simulated Agile developer workflows with Jira tickets, PR code reviews, and LORs.", icon: "Briefcase" },
      { title: "Placement Training", desc: "Mock technical interviews, system design, DSA problem solving, and resume polish.", icon: "GraduationCap" },
      { title: "AI Workshops", desc: "Generative AI APIs, LLMs, prompt engineering, and autonomous agent building.", icon: "Sparkles" },
      { title: "Industry Projects", desc: "Real client-grade production capstones shippable to student GitHub portfolios.", icon: "Code2" },
    ],
    ctaText: "Partner With Us",
  },

  faqs: [
    {
      question: "Are NextGen Tech 1-Day experiences really suitable for absolute beginners?",
      answer: "Yes! Our 1-Day Experiences are structured step-by-step. We start with fundamental concepts and guide you through building a live application with step-by-step code templates and dedicated mentor assistance.",
    },
    {
      question: "What is the difference between a 1-Day Experience, Internship, and Bootcamp?",
      answer: "1-Day Experiences are fast-paced hands-on sprints where you build and deploy one specific project. Internships simulate 4+ weeks of real software team workflows (Jira tickets, PR code reviews, standups). Bootcamps are intensive multi-week comprehensive tracks covering deep technical domains.",
    },
    {
      question: "Do I get a verified certificate upon completion?",
      answer: "Absolutely. Every graduate receives an encrypted, verifiable digital certificate with a custom URL and QR code that can be embedded directly into LinkedIn profiles and resumes.",
    },
    {
      question: "What hardware or software prerequisites do I need?",
      answer: "All you need is a laptop (Windows, Mac, or Linux), Google Chrome or modern browser, stable internet connection, and free accounts on GitHub and Vercel. We provide all cloud development environments.",
    },
    {
      question: "How does the simulated Developer Internship work?",
      answer: "You join a Discord team room with 4-5 peers and a senior engineer mentor. You work on sprint tasks via a Kanban board, push code to GitHub, submit pull requests, attend async standups, and receive thorough code reviews.",
    },
    {
      question: "What if I miss a live session or need extra help?",
      answer: "All live sessions are recorded in HD and available in your student portal immediately. You also have 24/7 access to our active mentor Discord channels for code debugging.",
    },
    {
      question: "Are there group discounts for college student batches?",
      answer: "Yes! We offer special college group pricing and campus ambassador discounts for groups of 5+ students. Contact us or use our 'Partner With Us' form to request a group pass.",
    },
    {
      question: "What is the refund policy?",
      answer: "We offer a 100% money-back guarantee for all 1-Day Experiences if you request a refund within 2 hours of the workshop start time.",
    },
  ],

  finalCta: {
    headline: "YOUR FIRST TECH EXPERIENCE IS ONE DAY AWAY.",
    subtext: "No boring lectures. No passive videos. Write real code, deploy live applications, and launch your software career today.",
    ctaText: "START LEARNING NOW",
    trustBadge: "⚡ Over 500+ students already enrolled. No prior experience required.",
  },

  footer: {
    tagline: "Empowering the next generation of software engineers through hands-on, high-impact technical training.",
    columns: [
      {
        title: "Programs",
        links: [
          { label: "1-Day Experiences", href: "/programs" },
          { label: "Program Details & Syllabus", href: "/program-details" },
          { label: "Developer Internships", href: "/internships" },
          { label: "Technical Bootcamps", href: "/bootcamps" },
          { label: "MERN Stack Sprint", href: "/bootcamps" },
        ],
      },
      {
        title: "Technologies",
        links: [
          { label: "Development", href: "/courses" },
          { label: "Data Analytics", href: "/courses" },
          { label: "AI & Machine Learning", href: "/courses" },
          { label: "UI/UX Design", href: "/courses" },
          { label: "Cloud & DevOps", href: "/courses" },
        ],
      },
      {
        title: "Company & Portals",
        links: [
          { label: "About Us", href: "/about" },
          { label: "Trainers & Mentors", href: "/trainers" },
          { label: "Certificates", href: "/certificates" },
          { label: "FAQs", href: "/faq" },
          { label: "Student Login / Signup", href: "/login" },
        ],
      },
      {
        title: "Student Dashboard",
        links: [
          { label: "My Dashboard", href: "/dashboard" },
          { label: "My Courses", href: "/my-courses" },
          { label: "My Certificates", href: "/my-certificates" },
          { label: "Admin Console", href: "/admin" },
          { label: "For Colleges & TPOs", href: "/colleges" },
        ],
      },
    ],
    socials: [
      { name: "GitHub", href: "#", icon: "Github" },
      { name: "Twitter", href: "#", icon: "Twitter" },
      { name: "LinkedIn", href: "#", icon: "Linkedin" },
      { name: "YouTube", href: "#", icon: "Youtube" },
      { name: "Discord", href: "#", icon: "MessageSquare" },
    ],
  },
};
